version: '3.8' 

services:
  modelserver:
    image: modelserver 
    build:
      context: . 
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"  
    volumes:
      - ./logs:/app/logs 
    restart: unless-stopped  
